apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: guestbook-app
  namespace: open-cluster-management
  annotations:
    apps.open-cluster-management.io/deployables: ''
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - guestbook-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: guestbook-app-subscription-1
  namespace: open-cluster-management
  annotations:
    apps.open-cluster-management.io/deployables: 'open-cluster-management/guestbook-app-subscription-1-resources-guestbook-redis-slave-service,open-cluster-management/guestbook-app-subscription-1-resources-guestbook-runasanyuid-serviceaccount,open-cluster-management/guestbook-app-subscription-1-resources-guestbook-anyuid-securitycontextconstraints,open-cluster-management/guestbook-app-subscription-1-resources-guestbook-frontend-service,open-cluster-management/guestbook-app-subscription-1-resources-guestbook-redis-master-service,open-cluster-management/guestbook-app-subscription-1-resources-guestbook-redis-master-deployment,open-cluster-management/guestbook-app-subscription-1-resources-guestbook-frontend-deployment,open-cluster-management/guestbook-app-subscription-1-resources-guestbook-guestbook-route-route,open-cluster-management/guestbook-app-subscription-1-resources-guestbook-redis-slave-deployment'
    apps.open-cluster-management.io/git-branch: ''
    apps.open-cluster-management.io/git-path: resources/guestbook
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: guestbook-app
    app.kubernetes.io/part-of: guestbook-app
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  channel: ggithubcom-open-cluster-management-deploy-ns/ggithubcom-open-cluster-management-deploy
  placement:
    placementRef:
      name: guestbook-app-placement-1
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: guestbook-app-placement-1
  namespace: open-cluster-management
  labels:
    app: guestbook-app
spec:
  clusterSelector:
    matchLabels:
      name: sno22
